env    = "dev"
region = "us-west-2"
ami_id = "ami-05f991c49d264708f"
vpc_cidr          = "10.0.0.0/16"
availability_zones = ["us-west-2a", "us-west-2b"]
private_subnets    = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnets     = ["10.0.101.0/24", "10.0.102.0/24"]
account_id            = "228281126655"            # <-- Replace with your actual AWS account ID
public_subnet         = "subnet-xxxxxxxx"         # <-- One of the public subnet IDs (for control plane)
vpc_id                = "vpc-xxxxxxxx"            # <-- Your VPC ID
key_name              = "Majed_Discord_key"       # <-- Your EC2 key pair name
worker_ami_id         = "ami-05f991c49d264708f"    # Same or different AMI from control plane
worker_instance_type  = "t3.large"                # Optional (already has default)
instance_profile_name = "k8s-worker-profile-dev"   # Must match name from IAM instance profile
vpc_subnet_ids        = ["subnet-xxx1", "subnet-xxx2"]  # Real subnet IDs matching private_subnets
