replicaCount: 1

image:
  repository: majedsaade/yoloservice_build_prod
  tag: "5"
  pullPolicy: IfNotPresent

service:
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

