replicaCount: 1

image:
  repository: majedsaade/yoloservice_build_prod
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
