global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-instances'
    static_configs:
      - targets:
          - '10.0.1.10:8889'   # polybot-dev
          - '10.0.1.11:8889'   # polybot-prod
          - '10.0.1.12:8889'   # yolo-dev
          - '10.0.1.13:8889'   # yolo-prod
