apiVersion: v2
name: monitoring
version: 0.1.0
description: A Helm chart for deploying Prometheus and Grafana for cluster monitoring
keywords:
  - monitoring
  - prometheus
  - grafana
type: application
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "7.3.9"
    repository: "https://grafana.github.io/helm-charts" 