apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # optional: controls sync order in app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/MajedSaade/PolybotInfraFursa
    targetRevision: main
    path: k8s/argo-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
