apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-token
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: discord-token
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: /polybot/dev/DISCORD_BOT_TOKEN
