replicaCount: 1

image:
  repository: ghcr.io/your-org/polybot
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: polybot.fursa.click
      paths:
        - path: /
          pathType: Prefix
  tls: []  # You can add ACM cert secrets here

resources: {}
