name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.MONITORING_EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MONITORING_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Package code for upload
        run: |
          echo "Zipping without .git..."
          zip -r monitoring-stack.zip . -x "*.git*" "*.venv*" "__pycache__/*"

      - name: Upload to EC2 and deploy
        run: |
          echo "Uploading zip to EC2..."
          scp monitoring-stack.zip ubuntu@${{ secrets.MONITORING_EC2_HOST }}:~/

          echo "Running remote deployment..."
          ssh -tt ubuntu@${{ secrets.MONITORING_EC2_HOST }} << 'EOF'
            set -eux
            rm -rf ~/monitoring-stack
            unzip -o monitoring-stack.zip -d ~/monitoring-stack
            rm monitoring-stack.zip
            cd ~/monitoring-stack
            docker compose down || true
            docker compose pull
            docker compose up -d
            docker ps
          EOF
