name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.MONITORING_EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MONITORING_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload files to EC2 using rsync (excluding .git)
        run: |
          rsync -avz --exclude='.git' --exclude='__pycache__' --exclude='.venv' ./ \
            ubuntu@${{ secrets.MONITORING_EC2_HOST }}:~/monitoring-stack

      - name: Run remote deployment on EC2
        run: |
          ssh -tt ubuntu@${{ secrets.MONITORING_EC2_HOST }} << 'EOF'
            set -eux

            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl enable docker
              sudo usermod -aG docker \$USER
            fi

            # Install Docker Compose v2 if not present
            if ! docker compose version &> /dev/null; then
              echo "Installing Docker Compose v2..."
              mkdir -p ~/.docker/cli-plugins/
              curl -SL https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64 \
                -o ~/.docker/cli-plugins/docker-compose
              chmod +x ~/.docker/cli-plugins/docker-compose
            fi

            # Run deployment with Docker Compose
            cd ~/monitoring-stack

            # Allow docker group permissions to take effect without logout
            newgrp docker <<EOC
              docker compose pull
              docker compose down || true
              docker compose up -d
              docker ps
             EOC
             EOF
