name: Deploy Monitoring Stack

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.MONITORING_EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MONITORING_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload files
        run: |
          rsync -avz --delete --exclude='.git' --exclude='__pycache__' --exclude='.venv' \
            ./ ubuntu@${{ secrets.MONITORING_EC2_HOST }}:~/monitoring-stack/

      - name: Deploy
        run: |
          ssh ubuntu@${{ secrets.MONITORING_EC2_HOST }} << 'EOF'
          set -e
          
          if ! command -v docker >/dev/null 2>&1; then
            sudo apt-get update -q
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo usermod -aG docker ubuntu
          fi
          
          if ! docker compose version >/dev/null 2>&1; then
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            sudo curl -sL https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64 \
              -o /usr/local/lib/docker/cli-plugins/docker-compose
            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          fi
          
          cd ~/monitoring-stack
          sudo docker compose down || true
          sudo docker compose pull
          sudo docker compose up -d
          sudo docker compose ps
          EOF