name: Deploy Monitoring Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MONITORING_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MONITORING_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy monitoring stack files to EC2
        run: |
          echo "Uploading monitoring files to EC2..."
          scp -o StrictHostKeyChecking=no -r . ubuntu@${{ secrets.MONITORING_EC2_HOST }}:~/monitoring-stack

      - name: SSH into EC2 and deploy services
        run: |
          echo "Running remote docker compose..."
          ssh -tt ubuntu@${{ secrets.MONITORING_EC2_HOST }} << 'EOF'
            set -eux  # Show commands + exit on error
            cd ~/monitoring-stack

            echo "Pulling latest images..."
            docker compose pull

            echo "Stopping previous stack (if exists)..."
            docker compose down || true

            echo "Starting up stack..."
            docker compose up -d

            echo "Current containers:"
            docker ps -a
          EOF
