name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.MONITORING_EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MONITORING_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload files to EC2 with rsync (excluding .git)
        run: |
          echo "Syncing files to EC2..."
          rsync -avz --exclude='.git' --exclude='__pycache__' --exclude='.venv' ./ \
            ubuntu@${{ secrets.MONITORING_EC2_HOST }}:~/monitoring-stack

      - name: Run remote deployment on EC2
        run: |
          ssh -tt ubuntu@${{ secrets.MONITORING_EC2_HOST }} << 'EOF'
            set -eux

            # Ensure docker-compose is ready
            cd ~/monitoring-stack

            docker compose pull
            docker compose down || true
            docker compose up -d
            docker ps
          EOF
