name: Provision Infrastructure

on:
  push:
    branches:
      - main
      - feature/tf_cluster_infrastructure

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="region.us-west-2.dev.tfvars"

    - name: Terraform Output (control plane public IP)
      id: tf_output
      run: |
            terraform output -raw control_plane_public_ip > control_plane_ip.txt

    - name: Upload control plane IP artifact
      uses: actions/upload-artifact@v4
      with:
        name: control_plane_ip
        path: control_plane_ip.txt
