name: Provision Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="region.us-west-2.dev.tfvars"

    - name: Store control plane IP in AWS SSM
      run: |
        CONTROL_PLANE_IP=$(terraform output -raw control_plane_public_ip)
        echo "✅ Control plane IP: $CONTROL_PLANE_IP"
        aws ssm put-parameter \
          --name "/k8s/control-plane-ip" \
          --value "$CONTROL_PLANE_IP" \
          --type String \
          --overwrite

    - name: Upload DEV Discord token to SSM
      run: |
        aws ssm put-parameter \
          --name "/polybot/dev/DISCORD_BOT_TOKEN" \
          --value "${{ secrets.DISCORD_BOT_TOKEN_DEV }}" \
          --type "SecureString" \
          --overwrite

    - name: Upload PROD Discord token to SSM
      run: |
        aws ssm put-parameter \
          --name "/polybot/prod/DISCORD_BOT_TOKEN" \
          --value "${{ secrets.DISCORD_BOT_TOKEN_PROD }}" \
          --type "SecureString" \
          --overwrite